#!/usr/bin/env bash

# Update packages and install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create index.html
echo "Hello World!" | sudo tee /var/www/html/index.html

# Define a variable for the custom HTTP response header
header_value="X-Served-By: $HOSTNAME"

# Configure Nginx to add the custom HTTP response header
header_config="add_header $header_value;"

# Modify Nginx configuration to include the custom header
header_config_block="listen 80 default_server;\n\t$header_config\n\tserver_name _;"

# Replace the server block with the updated configuration
sudo sed -i "s/listen 80 default_server;/$header_config_block/" /etc/nginx/sites-enabled/default

# Test nginx configuration for syntax errors
sudo nginx -t

# Restart nginx after implementing changes
sudo service nginx restart

