#!/usr/bin/env bash
# This configure an Nginx server to listen on port 8o

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
